# ============================================================
# Семантический слой Lightdash для Jaffle Shop (DuckDB)
# ============================================================
# Метрики и связи моделей для самообслуживаемой аналитики в Lightdash.
# ============================================================

version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    config:
      meta:
        primary_key: customer_id
        joins:
          - join: orders
            sql_on: ${customers.customer_id} = ${orders.customer_id}
            relationship: one-to-many
            label: Orders
        default_time_dimension:
          field: first_order
          interval: MONTH
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
        config:
          meta:
            metrics:
              unique_customers:
                type: count_distinct
                label: Unique customers
                description: Number of unique customers
        meta:
          dimension:
            type: number

      - name: first_name
        description: Customer's first name. PII.
        meta:
          dimension:
            type: string

      - name: last_name
        description: Customer's last name. PII.
        meta:
          dimension:
            type: string

      - name: first_order
        description: Date (UTC) of a customer's first order
        config:
          meta:
            dimension:
              type: date
              time_intervals: ["DAY", "WEEK", "MONTH", "YEAR"]
        meta:
          dimension:
            type: date

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order
        meta:
          dimension:
            type: date

      - name: number_of_orders
        description: Count of the number of orders a customer has placed
        meta:
          dimension:
            type: number

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders
        config:
          meta:
            metrics:
              total_customer_value:
                type: sum
                format: usd
                round: 2
                label: Total customer value
              average_customer_value:
                type: average
                format: usd
                round: 2
                label: Average customer value
        meta:
          dimension:
            type: number

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments
    config:
      meta:
        primary_key: order_id
        joins:
          - join: customers
            sql_on: ${orders.customer_id} = ${customers.customer_id}
            relationship: many-to-one
            label: Customer
        default_time_dimension:
          field: order_date
          interval: MONTH
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order
        config:
          meta:
            metrics:
              total_orders:
                type: count_distinct
                label: Total orders
              completed_orders:
                type: count_distinct
                label: Completed orders
                filters:
                  - is_completed: "true"
        meta:
          dimension:
            type: number

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
        meta:
          dimension:
            type: number

      - name: order_date
        description: Date (UTC) that the order was placed
        config:
          meta:
            dimension:
              type: date
              time_intervals: ["DAY", "WEEK", "MONTH", "YEAR", "QUARTER_NAME"]
        meta:
          dimension:
            type: date

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
        meta:
          dimension:
            type: string

      - name: is_completed
        description: Order has status completed
        config:
          meta:
            metrics:
              fulfillment_rate:
                type: average
                format: percent
                round: 1
                sql: "CASE WHEN ${is_completed} THEN 1 ELSE 0 END"
                label: Fulfillment rate
        meta:
          dimension:
            type: boolean

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null
        config:
          meta:
            metrics:
              total_revenue:
                type: sum
                format: usd
                round: 2
                label: Total revenue
              completed_revenue:
                type: sum
                format: usd
                round: 2
                label: Revenue (completed orders)
                filters:
                  - is_completed: "true"
              average_order_value:
                type: average
                format: usd
                round: 2
                label: Average order value
        meta:
          dimension:
            type: number

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null
        meta:
          dimension:
            type: number

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null
        meta:
          dimension:
            type: number

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null
        meta:
          dimension:
            type: number

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null
        meta:
          dimension:
            type: number
